name: Hello World
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'your name?'
jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Text
        run: echo "Hello World! from ${{ inputs.name }}"
    
