name: Hello World 2
on: 
 workflow_call:
   inputs:
       name:

       
#  schedule: 
#    - cron: '40 * * * *'
jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Text
        run: echo "{{ Hello, inputs.name 2.... }}"
