name: 📅 Schedule Workflow Dispatch
on:
  schedule:
    # - cron: '0 */1 * * *' # every hour
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: 'in 1 hour'
      name:
        description: 'enter name for the workflow run?'
concurrency:
  group: schedule${{ github.event.inputs.date }}
  cancel-in-progress: true

jobs:
  schedule:
    name: 📅 Schedule
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/schedule@v1.3
        with:
          github-token: ${{ secrets.TOKEN }}
          #github-token: ${{ github.token }}
          date: ${{ github.event.inputs.date }}
          workflow: 'hello_world.yml'
          timezone: 'Europe/Stockholm' # US/Central, US/Pacific
          wait-ms: 45000
          #inputs: '{"name": "paulio"}'
          inputs: ${{ toJson(github.event.inputs) }}
